### PR TITLE
sick leave and holiday buttons added

### PR DESCRIPTION
**Pull request by MichaelSp**
In order to work on this project I had to update to API SDK 24 - target SDK 27

Signed-off-by: Michael Sprauer <Michael.Sprauer@sap.com>

### CODE REVIEW

**Comment by mathisdt** [comment]
Thanks for your contribution! :smile:
Please consider the following points I found while testing your branch:

- The new buttons insert new events at 9 a.m. (type IN) and 5 p.m. (type OUT), regardless of how long the working day of the user might be. This is determined by how long his week is (in hours) and how many days he works on. Both can be changed in the Options view - section "Flexi Time Balancing".
- The events are inserted even if there are other events "in the way" - it does not make sense to insert a "9 to 5" sick leave e.g. if I already clocked in at 9.10 a.m. and worked 5 hours.
- The "Multi-Insert" feature (available from the menu) seems to be similar to what you want to archive but it is not as visible as the buttons. It might be a good idea to combine the features. Also, please start the "non-standard" periods at midnight as that makes it clearer that these periods are not normal working time (as "Multi-Insert" does).

**Comment by MichaelSp** [comment]
Hi @mathisdt Thanks for your feedback.
I changed my PR to:
 * Don't clock in if already clocked in https://github.com/MichaelSp/trackworktime/blob/master/app/src/main/java/org/zephyrsoft/trackworktime/timer/TimerManager.java#L879
 * Take the working day into consideration

New Feature:
 * you can press the buttons several time in order to create the event on subsequent days for the same week

You are right, I was missing the feature "Multi-Insert". Frankly I wasn't so sure what it supposed to be and never tried it. However I think the buttons are more self explanatory and easier to handle.

**Comment by mathisdt** [comment]
It seems that there still are some problems when there are already events on the same day. I pressed the "sick leave" button a few times and got these events: [screenshot 1](https://user-images.githubusercontent.com/1932462/35196108-03b1daaa-fece-11e7-8bc3-06bd24e994a3.png)

I would prefer not to let the buttons generate events for other days than the current one. This may be confusing for users as it is unexpected. Maybe you could create a dialog which asks the user for how many days he wants to clock a sick leave/holiday?

I also noticed that the inserted periods still start at 9 a.m. - please make them start at midnight as that makes it clearer that these periods are not normal working time (like "Multi-Insert").

Regarding the TravisCI issue, the information at https://github.com/travis-ci/travis-ci/issues/6801 or https://github.com/travis-ci/docs-travis-ci-com/issues/779 may help.

**Comment by mathisdt** [comment]
This PR seems to be abandoned, so it will be closed.

**Pull request closed without merging**
