### PR TITLE
App widget

### PR DESCRIPTION
**Pull request by WildOrangutan**
#118

### CODE REVIEW

**Comment by WildOrangutan** [comment]
This should cause much conflicts with that other mega PR.

Here's an image (below), so you have better understanding of how things look. Let me know if there's anything you would like to change.

widget_preview

**Comment by mathisdt** [comment]
Thanks for the PR! I just tested it and it works really nice on API level 28. But when I tested on API level 19 (the app is for API level 16 and up) the widget didn't initialize at all. Is that a known problem? If so, could the widget display a message if it is added under an incompatible API level?

**Comment by WildOrangutan** [comment]
I guess it wouldn't be Android, if everything would work off the bat 😄. I had to look at TextView source code, to find which APIs are problematic. Should work now.

Also, if it's not too much to ask, tagging this PR with `hacktoberfest` would be really nice for me 😊

**Comment by mathisdt** [comment]
Great, thanks!

**Comment by WildOrangutan** [comment]
Don't forget to close the issue

**Comment by mathisdt** [comment]
When a PR is merged, it's also closed. (BTW: I can't close it anymore, the "Close" button below has disappeared.)

**Pull request merged**
