### PR TITLE
Save logs to internal storage

### PR DESCRIPTION
**Pull request by WildOrangutan**
#139

### CODE REVIEW

**Comment by mathisdt** [comment]
Is it possible to read the log files (containing the most recent entries) if the app doesn't start anymore? It might sound like a remote possibility, but that was one of the reasons why I put the logs into the external storage in the first place. I saw that you copy the log file to the documents area, but that only seems to happen when triggered manually.

Is the proposal of having the user select a documents directory (using `ACTION_OPEN_DOCUMENT_TREE`, see [comment](https://github.com/mathisdt/trackworktime/issues/139#issuecomment-938433732)) not working out well in practice? I think needing only one user interaction for storing any file at any time would be preferable to making the user select the target file every time again. (Plus we could store the log files there directly and be able to see them even if the app doesn't start anymore.)

**Comment by WildOrangutan** [comment]
> Is it possible to read the log files (containing the most recent entries) if the app doesn't start anymore?

Not possible, at least not without rooting your phone.

> Is the proposal of having the user select a documents directory (using `ACTION_OPEN_DOCUMENT_TREE`, see [comment](https://github.com/mathisdt/trackworktime/issues/139#issuecomment-938433732)) not working out well in practice? I think needing only one user interaction for storing any file at any time would be preferable to making the user select the target file every time again. (Plus we could store the log files there directly and be able to see them even if the app doesn't start anymore.)

Didn't check, will try it out.
Tough there could be the same problem, if app crashes before user selects that directory. I think acra should cover that case.

> EDIT: The [documentation](https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory) seems to support the idea, it should generally be possible. I don't know if we can suggest (via intent) that the user creates a new (empty) directory, but we could also show a message to the user before asking for the permission so he has to create the directory for TWT manually. If it is explained well, it should work as it's only a one-time thing.

As far as I've read it should be possible. You gain full permissions to do whatever you like inside that directory.
The only thing I'm concerned is if this access to directory is persistent. Will check it out.

**Comment by WildOrangutan** [comment]
What you proposed is possible. Downside is that you can't use Tinylog out of the box, since you can't really work with `File`s.

**Comment by mathisdt** [comment]
I think it would be possible to use Tinylog, but with a [custom writer](https://tinylog.org/v2/extending/#custom-writer) which knows how to append text to the files in the permitted directory.

**Comment by mathisdt** [comment]
I'm currently putting something together to replace the external storage access completely and I arrived at the opinion that the log file should stay out of scope for that because it probably would be really slow. The log file is written to often, and document providers don't seem to be made for that use case.

So thanks for the PR and sorry I didn't take the time to think this through before.

**Pull request merged**
